# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4bd0debc42fa9e2f2583ec5e311d1ef52cb44f22b44ee41751595e1cbb462dc324ef8ae29b23ca693a000618a20017228e76363b89da8076f7076cd0f8dbaa61

test:
  secret_key_base: 10398810bb6f71912b830ab8c8544f058d42522b2e7ee6d20267705c7fe5fcd632c1dd927c478f0aa8488c3a2a9d60b828d5a13c127d4afbe579a01c1bbf4813

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
